exclude = [
    "env",
    "venv",
    ".pyenv",
    ".pytest_cache",
    "*/__pycache__/*",
    "*/migrations/*",
    "docs",
]

line-length = 100

target-version = "py38"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint.isort.sections]
django = ["django"]
drf = ["rest_framework"]

[lint.isort]
section-order = [
  "future",
  "standard-library",
  "django",
  "drf",
  "third-party",
  "first-party",
  "local-folder",
]
